import React from 'react';
import { StyleProp, ViewStyle } from 'react-native';
import {
  AlarmClock,
  Armchair,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  BatteryCharging,
  Bean,
  Bell,
  Bookmark,
  CakeSlice,
  Calendar,
  CalendarCheck,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  CircleHelp,
  ClipboardList,
  Clock,
  Coffee,
  Construction,
  CreditCard,
  Croissant,
  CupSoda,
  Dice5,
  Eye,
  EyeOff,
  FileText,
  Gift,
  Headphones,
  Heart,
  Home,
  Image,
  Laptop,
  Leaf,
  Lock,
  LogOut,
  Mail,
  MapPin,
  MessageCircle,
  Milk,
  Package,
  PackageCheck,
  PartyPopper,
  PawPrint,
  Phone,
  Pizza,
  ReceiptText,
  RotateCcw,
  Salad,
  Search,
  Settings,
  Shield,
  ShoppingBag,
  ShoppingCart,
  Soup,
  Sprout,
  Star,
  Store,
  Tag,
  Trash2,
  Trophy,
  Truck,
  User,
  Users,
  Utensils,
  Wallet,
  Wheat,
  Wifi,
  X,
  Zap,
} from 'lucide-react-native';

type AppIconProps = {
  name?: string;
  size?: number;
  color?: string;
  strokeWidth?: number;
  fill?: string;
  style?: StyleProp<ViewStyle>;
};

const ICONS: Record<string, any> = {
  all: Coffee,
  arrow: ArrowRight,
  'arrow-up-right': ArrowUpRight,
  art: Image,
  back: ArrowLeft,
  bakery: Croissant,
  bell: Bell,
  bookmark: Bookmark,
  bubbletea: CupSoda,
  cafe: Coffee,
  camera: Camera,
  card: CreditCard,
  cart: ShoppingCart,
  check: Check,
  chevron_down: ChevronDown,
  close: X,
  coffee: Coffee,
  completed: Check,
  construction: Construction,
  date: Heart,
  delivery: Truck,
  desserts: CakeSlice,
  dine_in: Armchair,
  drinks: Coffee,
  email: Mail,
  eye: Eye,
  eye_off: EyeOff,
  faq: CircleHelp,
  filter: Settings,
  food: Utensils,
  gift: Gift,
  healthy: Salad,
  help: CircleHelp,
  home: Home,
  kitchen: Soup,
  location: MapPin,
  lock: Lock,
  logout: LogOut,
  notification: Bell,
  orders: ClipboardList,
  package: Package,
  payments: CreditCard,
  phone: Phone,
  photo: Camera,
  pizza: Pizza,
  points: Star,
  popular: Star,
  preorder: ShoppingBag,
  privacy: Shield,
  receipt: ReceiptText,
  refresh: RotateCcw,
  reservation: Armchair,
  rewards: Gift,
  search: Search,
  secure: Lock,
  settings: Settings,
  support: Headphones,
  takeout: Package,
  tea: Coffee,
  time: Clock,
  trash: Trash2,
  trending: Trophy,
  user: User,
  users: Users,
  vegan: Sprout,
  wallet: Wallet,
  wifi: Wifi,
  work: Laptop,
  zap: Zap,

  '☕': Coffee,
  '🧋': CupSoda,
  '🥐': Croissant,
  '🍰': CakeSlice,
  '🧁': CakeSlice,
  '🫖': Coffee,
  '💻': Laptop,
  '💕': Heart,
  '🛒': ShoppingCart,
  '⭐': Star,
  '🎁': Gift,
  '🛵': Truck,
  '🔒': Lock,
  '📞': Phone,
  '✉': Mail,
  '✉️': Mail,
  '🪑': Armchair,
  '👥': Users,
  '🔔': Bell,
  '💳': CreditCard,
  '⚙️': Settings,
  '⚙': Settings,
  '❓': CircleHelp,
  '📄': FileText,
  '📋': ClipboardList,
  '👛': Wallet,
  '📤': LogOut,
  '📸': Camera,
  '←': ArrowLeft,
  '→': ArrowRight,
  '›': ChevronRight,
  '▾': ChevronDown,
  '×': X,
  '✕': X,
  '✓': Check,
  '✅': Check,
  '❌': X,
  '🔄': RotateCcw,
  '🗑': Trash2,
  '🗑️': Trash2,
  '🎧': Headphones,
  '📦': Package,
  '📅': Calendar,
  '📆': CalendarCheck,
  '🕐': AlarmClock,
  '✏️': FileText,
  '📭': Mail,
  '🎉': PartyPopper,
  '🏁': Trophy,
  '🥡': Package,
  '🚚': Truck,
  '📱': User,
  '🔐': Lock,
  '🌿': Leaf,
  '💧': Zap,
  '🧺': ShoppingBag,
  '🥛': Milk,
  '🌾': Wheat,
  '🌰': Bean,
  '🫘': Bean,
  '🌱': Sprout,
  '⚡': Zap,
  '🛡️': Shield,
  '🛡': Shield,
  '💬': MessageCircle,
  '🌙': Circle,
  '📍': MapPin,
  '🌐': Store,
  '🏗️': Construction,
  '🍽️': Utensils,
  '🍽': Utensils,
  '🍴': Utensils,
  '🛍': ShoppingBag,
  '🛍️': ShoppingBag,
  '🏠': Home,
  '🔖': Bookmark,
  '📶': Wifi,
  '🔋': BatteryCharging,
  '🐾': PawPrint,
  '📷': Camera,
  '🎨': Image,
  '🎲': Dice5,
  '🥇': Trophy,
  '🏷️': Tag,
  '🏪': Store,
  '📬': Mail,
  '🧾': ReceiptText,
  '💰': Wallet,
  '🍕': Pizza,
  '🥗': Salad,
  '🌃': Store,
};

export default function AppIcon({
  name,
  size = 18,
  color = '#1A1A1A',
  strokeWidth = 2,
  fill = 'none',
  style,
}: AppIconProps) {
  const Icon = ICONS[name || ''] || Circle;
  return <Icon size={size} color={color} strokeWidth={strokeWidth} fill={fill} style={style} />;
}
